name: CI

on:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug & syntax check app.py
        run: |
          set -e
          python --version
          ls -la
          echo "----- head app.py (1..140) -----"
          sed -n '1,140p' app.py || true
          python - << 'PY'
import sys, pathlib
p = pathlib.Path("app.py")
print("Exists:", p.exists(), "Size:", p.stat().st_size if p.exists() else 0)
src = p.read_text(encoding="utf-8")
compile(src, "app.py", "exec")
print("✅ Python compile OK")
PY

      - name: Run flake8 (lenient for now)
        run: |
          python -m pip install flake8
          flake8 app.py --extend-ignore=E999 || true

      - name: Run pytest (only if tests exist)
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: |
          python -m pip install pytest
          pytest -q