name: Python application (compat)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Προαιρετικό debug για να βλέπεις τι τρέχει
      - name: Debug & syntax check app.py
        run: |
          python --version
          ls -la
          python - << 'PY'
import pathlib, sys
p = pathlib.Path("app.py")
print("Exists:", p.exists(), "Size:", p.stat().st_size if p.exists() else 0)
src = p.read_text(encoding="utf-8")
compile(src, "app.py", "exec")
print("✅ Python compile OK")
PY

      # Lenient flake8 (δεν μπλοκάρει το build)
      - name: Lint with flake8 (lenient)
        run: |
          python -m pip install flake8
          flake8 app.py --extend-ignore=E999 || true

      # Τρέξε tests μόνο αν υπάρχουν
      - name: Test with pytest (only if tests exist)
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: |
          python -m pip install pytest
          pytest -q